### ISSUE TITLE
not detect anything in the frames

### ISSUE THREAD

**Issue by HsuWanTing** [parvkpr/Accident-avoidance-deepsortyoloFCRN#1]
Hi,

I downloaded the models from [iro-cp/FCRN-DepthPrediction](https://github.com/iro-cp/FCRN-DepthPrediction#models) and [Qidian213/deep_sort_yolov3](https://github.com/Qidian213/deep_sort_yolov3#quick-start). Then, I changed the video path to my own video and run `python dmo.py`. However, there is nothing been detected. The number of detected boxes is always 0 for every frame. Is there anything wrong with my setup?

**Comment by parvkpr** [comment]
Hey, 
Did you download the weights file? Make sure to run deep_sort_yolov3 individually first. If the detection is a problem it's because you haven't configured deep_sort_yolov3 properly.

**Comment by HsuWanTing** [comment]
I found my problem. I copied `yolo.py` from [Qidian213/deep_sort_yolov3](https://github.com/Qidian213/deep_sort_yolov3). But it only draw boxes for class person because of [line 100 and line 101 in yolo.py](https://github.com/Qidian213/deep_sort_yolov3/blob/master/yolo.py#L100).
I commented these two lines then the detector works now.
